name: monorepo_test
publish_to: none

environment:
  sdk: ^3.9.2

dev_dependencies:
  melos: ^7.1.1

workspace:
  - app/first_app
  - app/second_app
  - feature/first_feature
  # - package/core

melos:
  scripts:
    generate:
      run: melos exec -c 1 --depends-on build_runner -- dart run build_runner build