name: core
description: Things that every featue or/and feature needs
publish_to: https://onepub.dev/api/apavavuhno/
repository: https://github.com/damjan-pantic-metaswiss/monorepo_test/tree/main/package/core
resolution: workspace
version: 2.0.0

environment:
  sdk: ^3.9.0
  flutter: '>=3.35.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0
